### ISSUE TITLE
Use default values in schemas

### ISSUE THREAD

**Issue by D3lux3** [otsokarhu/VLFantasy#3]
Use default values in schemas([https://mongoosejs.com/docs/defaults.html](https://mongoosejs.com/docs/defaults.html)) instead of creating them in creation time:
`
const createFantasyTeam = async (body: any): Promise<FantasyTeamPopulated> => {
  const fantasyTeam = new FantasyTeam({
    ...body,
    runners: [],
    points: 0,
  });
`
To this:
`
const createFantasyTeam = async (body: any): Promise<FantasyTeamPopulated> => {
  const fantasyTeam = new FantasyTeam({
    ...body,
  });
`

**Comment by otsokarhu** [comment]
done
