### ISSUE TITLE
Is finding users before deleting them by id unnecessary?

### ISSUE THREAD

**Issue by D3lux3** [otsokarhu/VLFantasy#5]
I have not worked with Mongoose for a long time, but i wondered if you reformat this function to just be
 `  await User.findByIdAndRemove(id);
`
instead of: 
`const deleteUser = async (id: string): Promise<void> => {
  const user = await getUser(id);
  if (!user) {
    throw new Error('User not found');
  }
  await User.findByIdAndRemove(id);
};
`
You should read and test what happens if you try to call the function with a id that does **not** exist.

**Comment by otsokarhu** [comment]
It wasn't necessary, fixed this
